'use client';
import {useEffect,useState} from 'react';
import {CircleDollarSign,Plus,Search,Trash2,WalletCards} from 'lucide-react';
import {api,errorMessage,money,useLocale} from '@/lib/arkan-client';
import {toast} from 'sonner';
const categories=[['supplier','الموردون','Suppliers'],['customer','العملاء','Customers'],['driver','السائقون','Drivers'],['purchase','المشتريات','Purchases'],['management','الإدارة','Administration'],['debt','الديون','Debts'],['rent','الإيجارات الشهرية','Monthly rent']] as const;
const empty=()=>({category:'supplier',party:'',entryDate:new Date(Date.now()+10800000).toISOString().slice(0,10),statement:'',description:'',debit:'',credit:''});
export default function AccountingPanel(){
 const{en,t}=useLocale(),[rows,setRows]=useState<any[]>([]),[summary,setSummary]=useState({debit:0,credit:0,balance:0,count:0}),[category,setCategory]=useState('all'),[query,setQuery]=useState(''),[form,setForm]=useState<any>(empty()),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setLoading(true);try{const value=await api('accounting&category='+(category==='all'?'':category)+'&q='+encodeURIComponent(query));setRows(value.entries);setSummary(value.summary);setError('')}catch(e){setError(errorMessage(e,en))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[category]);const name=(value:string)=>{const item=categories.find(x=>x[0]===value);return item?(en?item[2]:item[1]):value};const running=rows;
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);try{await api('saveLedger',{data:{...form,debit:Math.round(Number(form.debit||0)*100),credit:Math.round(Number(form.credit||0)*100)}});toast.success(t('تم حفظ الحركة','Entry saved'));setForm({...empty(),category:form.category});setOpen(false);await load()}catch(e){setError(errorMessage(e,en))}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm(t('حذف هذه الحركة؟','Delete this entry?')))return;setBusy(true);try{await api('deleteLedger',{id});toast.success(t('تم حذف الحركة','Entry deleted'));await load()}catch(e){setError(errorMessage(e,en))}finally{setBusy(false)}}
 return <div className="accounting-page"><div className="accounting-stats"><article><span><CircleDollarSign/></span><div><small>{t('إجمالي المدين','Total debit')}</small><b>{money(summary.debit,en)}</b></div></article><article><span><CircleDollarSign/></span><div><small>{t('إجمالي الدائن','Total credit')}</small><b>{money(summary.credit,en)}</b></div></article><article className={summary.balance<0?'negative':''}><span><WalletCards/></span><div><small>{t('الرصيد الحالي','Current balance')}</small><b>{money(summary.balance,en)}</b></div></article></div><section className="panel accounting-ledger"><div className="section-heading"><div><h2>{t('دفتر الحسابات','Accounts ledger')}</h2><p>{t('الموردون والعملاء والسائقون والمشتريات والديون والإيجارات','Suppliers, customers, drivers, purchases, debts and rent')}</p></div><button className="primary" onClick={()=>setOpen(!open)}><Plus size={18}/>{t('إضافة حركة','Add entry')}</button></div>
 {open&&<form className="accounting-form" onSubmit={save}><label>{t('القسم','Category')}<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(item=><option value={item[0]} key={item[0]}>{en?item[2]:item[1]}</option>)}</select></label><label>{t('اسم الجهة / الشخص','Party / person')}<input required maxLength={140} value={form.party} onChange={e=>setForm({...form,party:e.target.value})}/></label><label>{t('التاريخ','Date')}<input required type="date" value={form.entryDate} onChange={e=>setForm({...form,entryDate:e.target.value})}/></label><label>{t('البيان','Statement')}<input required maxLength={180} value={form.statement} onChange={e=>setForm({...form,statement:e.target.value})}/></label><label>{t('مدين','Debit')}<input type="number" min="0" step="0.01" dir="ltr" value={form.debit} onChange={e=>setForm({...form,debit:e.target.value})}/></label><label>{t('دائن','Credit')}<input type="number" min="0" step="0.01" dir="ltr" value={form.credit} onChange={e=>setForm({...form,credit:e.target.value})}/></label><label className="accounting-description">{t('الوصف','Description')}<textarea maxLength={1000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="accounting-form-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>{t('إلغاء','Cancel')}</button><button className="primary" disabled={busy}>{busy?t('جارٍ الحفظ…','Saving…'):t('حفظ الحركة','Save entry')}</button></div></form>}
 <p className="ops-form-note">{t('الرصيد = الدائن − المدين، حسب الفلاتر المختارة.','Balance = credit − debit for the selected filters.')}{summary.count>500&&t(' يتم عرض أحدث ٥٠٠ حركة، والإجماليات تشمل جميع النتائج.',' Showing the latest 500 entries; totals include all matches.')}</p>{error&&<p className="ops-error" role="alert">{error}</p>}<div className="accounting-filters"><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">{t('جميع الأقسام','All categories')}</option>{categories.map(item=><option value={item[0]} key={item[0]}>{en?item[2]:item[1]}</option>)}</select><form onSubmit={event=>{event.preventDefault();void load()}}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('بحث بالاسم أو البيان أو الوصف','Search party, statement or description')}/><button className="secondary">{t('بحث','Search')}</button></form></div><div className="ops-table"><table><thead><tr><th>{t('التاريخ','Date')}</th><th>{t('القسم','Category')}</th><th>{t('الجهة','Party')}</th><th>{t('البيان والوصف','Statement & description')}</th><th>{t('مدين','Debit')}</th><th>{t('دائن','Credit')}</th><th>{t('الرصيد','Balance')}</th><th></th></tr></thead><tbody>{running.map(row=><tr key={row.id}><td dir="ltr">{row.entryDate}</td><td><span className="ledger-category">{name(row.category)}</span></td><td><b>{row.party}</b></td><td><b>{row.statement}</b>{row.description&&<small>{row.description}</small>}</td><td className="ledger-debit">{row.debit?money(row.debit,en):'—'}</td><td className="ledger-credit">{row.credit?money(row.credit,en):'—'}</td><td><b>{money(row.running,en)}</b></td><td><button className="icon-button ops-danger" disabled={busy} onClick={()=>void remove(row.id)} aria-label={t('حذف','Delete')}><Trash2 size={17}/></button></td></tr>)}</tbody></table>{!rows.length&&!loading&&<div className="ops-empty"><WalletCards size={31}/><p>{t('لا توجد حركات حسابية بعد.','No accounting entries yet.')}</p></div>}{loading&&<div className="ops-empty"><p>{t('جارٍ تحميل الحسابات…','Loading accounts…')}</p></div>}</div></section></div>;
}
