'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,CheckCircle2,ScanLine,ShieldCheck,X,XCircle,LoaderCircle} from 'lucide-react';
import {api,Choice,errorMessage,useLocale} from '@/lib/arkan-client';
export default function AdminScanner({data,onBoarded}:{data:any;onBoarded:()=>void}){
  const {en,t}=useLocale();const trips=data.trips.filter((x:any)=>x.status==='active'&&!['in_transit','arrived'].includes(x.phase));
  const [trip,setTrip]=useState(trips[0]?.id||''),[token,setToken]=useState(''),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[active,setActive]=useState(false),[starting,setStarting]=useState(false);
  const resultPanel=useRef<HTMLElement>(null);
  const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),generation=useRef(0),scanLock=useRef(false),boardedCallback=useRef(onBoarded);
  useEffect(()=>{boardedCallback.current=onBoarded},[onBoarded]);
  useEffect(()=>{const panel=resultPanel.current;if(!result||!panel||!window.matchMedia('(max-width: 1023px)').matches)return;const rect=panel.getBoundingClientRect(),top=(document.querySelector('.ops-topbar')?.getBoundingClientRect().bottom??0)+12,bottom=(document.querySelector('.ops-bottom-nav')?.getBoundingClientRect().top??window.innerHeight)-12;if(rect.top<top||rect.bottom>bottom)panel.scrollIntoView({block:'nearest',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})},[result]);
  const station=(id:string)=>data.entities.find((s:any)=>s.id===id)?.[en?'en':'ar']||id;
  function release(){generation.current++;if(timer.current)clearInterval(timer.current);timer.current=null;stream.current?.getTracks().forEach(track=>track.stop());stream.current=null}
  function stop(){release();setActive(false);setStarting(false)}
  useEffect(()=>()=>release(),[]);
  useEffect(()=>{if(!trips.some((x:any)=>x.id===trip)){stop();setTrip(trips[0]?.id||'');setResult(null)}},[data.trips]);
  async function scan(value:string){if(scanLock.current||!value.trim()||!trip)return;scanLock.current=true;stop();const request=generation.current;setBusy(true);setError('');try{const response=await api('scan',{token:value.trim(),trip});if(request===generation.current)setResult(response);if(response.status==='VALID')boardedCallback.current()}catch(e){if(request===generation.current)setError(errorMessage(e,en))}finally{scanLock.current=false;setBusy(false)}}
  async function start(){if(!trip||busy||starting)return;stop();const request=++generation.current;setStarting(true);setError('');setResult(null);try{
    const jsQR=(await import('jsqr')).default;if(request!==generation.current)return;
    const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:960}},audio:false});
    if(request!==generation.current||!video.current){media.getTracks().forEach(track=>track.stop());return}
    stream.current=media;video.current.srcObject=media;await video.current.play();if(request!==generation.current)return;setActive(true);setStarting(false);
    const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
    timer.current=setInterval(()=>{const v=video.current;if(!v||!v.videoWidth||!ctx||scanLock.current)return;canvas.width=v.videoWidth;canvas.height=v.videoHeight;ctx.drawImage(v,0,0);const image=ctx.getImageData(0,0,canvas.width,canvas.height);const qr=jsQR(image.data,image.width,image.height,{inversionAttempts:'dontInvert'});if(qr?.data)void scan(qr.data)},400);
  }catch{if(request===generation.current){stop();setError(t('تعذّر فتح الكاميرا. اسمح بالوصول إليها أو أدخل رمز التذكرة يدويًا.','Unable to open the camera. Allow camera access or enter the ticket token manually.'))}}}
  const labels:Record<string,string>={BOARDING_CLOSED:t('تم إغلاق الصعود بعد الانطلاق','Boarding closed after departure'),VALID:t('تم تسجيل الصعود','Boarding recorded'),INVALID:t('تذكرة غير صالحة','Invalid ticket'),ALREADY_USED:t('التذكرة مستخدمة مسبقًا','Already used'),WRONG_TRIP:t('التذكرة لرحلة أخرى','Wrong trip'),PAYMENT_PENDING:t('بانتظار الدفع والتأكيد','Awaiting payment and confirmation')};
  return <div className="scanner-layout"><section className="panel"><label>{t('الرحلة','Trip')}<Choice value={trip} onChange={v=>{stop();setTrip(v);setResult(null);setToken('')}} disabled={busy||starting} label={t('اختر رحلة','Choose a trip')} options={trips.map((x:any)=>({value:x.id,label:x.time+' · '+station(x.from_station)+(en?' → ':' ← ')+station(x.to_station)}))}/></label>
  {!trips.length&&<p className="ops-form-note">{t('لا توجد رحلات نشطة في التاريخ المحدد.','There are no active trips on the selected date.')}</p>}
  <div className="camera-view"><video ref={video} muted playsInline className={active?'':'hidden-video'}/>{!active&&<>{starting?<LoaderCircle className="animate-spin" size={50}/>:<ScanLine size={64}/>}<p>{starting?t('جارٍ فتح الكاميرا…','Opening camera…'):t('ضع رمز التذكرة داخل الإطار','Place the ticket QR inside the frame')}</p></>}<span className="camera-frame"/></div>
  <button className="primary wide" onClick={active||starting?stop:start} disabled={!trip||busy}>{active||starting?<X size={20}/>:<Camera size={20}/ >}{active||starting?t('إيقاف الكاميرا','Stop camera'):result?t('مسح التذكرة التالية','Scan next ticket'):t('تشغيل الكاميرا','Open camera')}</button>
  <form className="manual-scan" onSubmit={e=>{e.preventDefault();void scan(token)}}><label>{t('إدخال الرمز يدويًا','Enter ticket token manually')}<input value={token} onChange={e=>setToken(e.target.value)} dir="ltr" required autoComplete="off" autoCapitalize="off" spellCheck={false} aria-describedby="manual-ticket-help" placeholder={t('الصق رمز التذكرة كاملًا','Paste the full ticket code')}/></label><button className="secondary" disabled={busy||starting||!trip}>{busy?t('جارٍ التحقق…','Checking…'):t('تحقق وسجّل الصعود','Validate and record boarding')}</button></form><p className="manual-ticket-help" id="manual-ticket-help">{t('اطلب من المسافر فتح تذكرته من «حجوزاتي» والضغط على «نسخ» عند رمز التذكرة. تجده أيضًا في ملف PDF، ولدى الإدارة في تفاصيل الحجز. لكل مسافر ولكل اتجاه رمز مستقل.','Ask the passenger to open their ticket in My Bookings and tap Copy beside the ticket code. The code is also in the PDF and in the admin booking details. Each passenger and each leg has a separate code.')}</p>{error&&<p className="error" role="alert">{error}</p>}</section>
  <section ref={resultPanel} className={'scan-result '+(result?.status==='VALID'?'valid':result?'invalid':'')} aria-live="polite">{result?<>{result.status==='VALID'?<CheckCircle2 size={52}/>:<XCircle size={52}/>}<h2>{result.status==='VALID'&&result.test?t('نجحت التجربة — تم تسجيل الصعود','Test passed — boarding recorded'):labels[result.status]||t('تعذّر التحقق','Unable to validate')}</h2>{result.test&&<p>{t('تذكرة اختبار دون تحصيل مالي.','Test ticket. No payment collected.')}</p>}{result.name&&<h3>{result.name}</h3>}{result.seat&&<p>{t('المقعد','Seat')} <b>{result.seat}</b></p>}{result.time&&<p dir="ltr">{result.date} · {result.time}</p>}{result.boarded&&<p>{new Date(result.boarded).toLocaleTimeString(en?'en-GB':'ar-SA',{timeZone:'Asia/Riyadh'})}</p>}{result.status==='PAYMENT_PENDING'&&<p>{t('لم يُسجّل صعود المسافر.','Passenger boarding was not recorded.')}</p>}</>:<><ShieldCheck size={48}/><h2>{t('جاهز للتحقق','Ready to check in')}</h2><p>{t('اختر الرحلة ثم امسح رمز التذكرة.','Choose a trip, then scan its ticket.')}</p></>}</section></div>;
}
