'use client';
import {useState} from 'react';
import {api,errorMessage,money,useLocale} from '@/lib/arkan-client';
import {arabicStatus} from '@/lib/ticket-details';
export default function AdminPaymentControl({booking,onUpdated}:{booking:any,onUpdated:()=>Promise<void>}){
const{en,t}=useLocale();const[target,setTarget]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
const locked=booking.passengers?.some((p:any)=>p.boarded)||!['pending','demo','paid'].includes(booking.status);
async function save(){setBusy(true);setError('');try{await api('setPaymentStatus',{code:booking.code,status:target,expectedStatus:booking.status});setTarget('');await onUpdated()}catch(e){setError(errorMessage(e,en))}finally{setBusy(false)}}
return <section className="payment-admin"><h3>{t('إدارة الدفع النقدي','Cash payment management')}</h3><p>{t('قيمة الحجز','Booking amount')}: <strong>{money(booking.amount,en)}</strong></p>{locked?<p>{t('لا يمكن تعديل الدفع لحجز ملغى أو بعد تسجيل صعود أحد المسافرين.','Payment cannot be changed after boarding or for cancelled bookings.')}</p>:target?<div role="group" aria-label={t('تأكيد تحديث الدفع','Confirm payment update')}><p>{target==='paid'?t('هل استلمت المبلغ كاملًا نقدًا؟ سيصبح الحجز مدفوعًا ومتاحًا للصعود.','Have you received the full amount in cash? The booking will be marked paid and eligible for boarding.'):t('هل تريد تصحيح حالة الدفع إلى غير مدفوع؟ هذا الإجراء لا يعيد أي مبلغ للعميل ويوقف صلاحية الصعود.','Correct payment to unpaid? This does not refund the customer and will disable boarding.')}</p><div className="payment-actions"><button className="primary" type="button" disabled={busy} onClick={()=>void save()}>{busy?t('جارٍ الحفظ…','Saving…'):t('تأكيد التحديث','Confirm update')}</button><button className="secondary" type="button" disabled={busy} onClick={()=>setTarget('')}>{t('رجوع','Back')}</button></div></div>:<button type="button" className={booking.status==='paid'?'secondary':'primary'} onClick={()=>setTarget(booking.status==='paid'?'pending':'paid')}>{booking.status==='paid'?t('تصحيح الحالة إلى غير مدفوع','Correct status to unpaid'):t('تسجيل استلام المبلغ نقدًا','Record cash received')}</button>}{error&&<p className="error" role="alert">{error}</p>}{booking.paymentEvents?.length>0&&<details><summary>{t('سجل تغييرات الدفع','Payment history')}</summary><ol>{booking.paymentEvents.map((event:any)=><li key={event.id}><b>{en?(event.to==='paid'?'Paid':'Unpaid'):arabicStatus(event.to)}</b> · <bdi>{event.actor}</bdi> · {new Date(event.at).toLocaleString(en?'en-GB':'ar-SA',{timeZone:'Asia/Riyadh'})}</li>)}</ol></details>}</section>}
