'use client';
import {useEffect,useState} from 'react';
import {attendance,passengerTickets,passengerTitles,identityTypes,arabicStatus} from '@/lib/ticket-details';
import {BookingJourney} from './trip-status';
import BookingSummaryDownload from './booking-summary-download';
import TicketCode from './ticket-code';
export default function ArabicTickets({booking,stations}:{booking:any,stations:any[]}){
const[qrs,setQrs]=useState<Record<string,string>>({});useEffect(()=>{let live=true;import('qrcode').then(async m=>{const pairs=await Promise.all(booking.tickets.map(async(k:any)=>[k.id,await m.default.toDataURL(k.id,{width:220,margin:2})]));if(live)setQrs(Object.fromEntries(pairs))}).catch(()=>{});return()=>{live=false}},[booking]);
const station=(id:string)=>stations.find(s=>s.id===id)?.ar||id;
return <><section dir="rtl" lang="ar"><div className="ticket-heading"><span className={'badge '+(booking.status==='cancelled'?'cancelled':'')}>{arabicStatus(booking.status)}</span><h2 dir="ltr">{booking.code}</h2>{booking.paymentMethod==='cash'&&<p>طريقة الدفع: نقدًا (كاش)</p>}</div><div className="ticket-list">{passengerTickets(booking.tickets).map(legs=><article className="ticket-card" key={legs[0].id}><div className="ticket-top"><img src="/brand/logo-forest.png" width="120" height="60" alt="أركان المسار"/><strong>تذكرة {legs.length>1?'ذهاب وعودة':'ذهاب'}</strong></div><div className="ticket-passenger"><span className="label">المسافر</span><h3>{passengerTitles.find(x=>x.value===legs[0].title)?.ar} {legs[0].name}</h3><p>{identityTypes.find(x=>x.value===legs[0].identityType)?.ar||'وثيقة الهوية'}: <bdi>{legs[0].maskedId}</bdi></p></div>{legs.map((k,index)=>{const at=attendance(k.date,k.time);return <section className="ticket-leg" key={k.id}><span className="tag">{index?'رحلة العودة':'رحلة الذهاب'}</span><div className="ticket-body"><div><p className="ticket-station"><small>محطة المغادرة</small><strong>{station(k.from_station)}</strong></p><p className="ticket-station"><small>محطة الوصول</small><strong>{station(k.to_station)}</strong></p></div>{qrs[k.id]?<img src={qrs[k.id]} alt={'رمز صعود '+(index?'العودة':'الذهاب')} width="110" height="110"/>:<span>جارٍ تجهيز الرمز…</span>}</div><div className="ticket-details">{[['تاريخ الرحلة',k.date],['الحضور',at.time+(at.date!==k.date?' · '+at.date:'')],['الانطلاق',k.time],['المقعد',k.seat],['الحافلة',k.bus_plate||k.bus]].map(([label,value])=><div key={label}><span>{label}</span><strong dir="ltr">{value}</strong></div>)}</div><TicketCode token={k.id}/></section>})}<p className="ticket-footnote">جميع المواعيد بتوقيت السعودية. الحضور قبل الانطلاق بساعة.<br/>{booking.status==='paid'?'يرجى إبراز التذكرة ووثيقة الهوية الأصلية عند الصعود.':booking.status==='cancelled'?'هذه التذكرة ملغاة وغير صالحة للصعود.':'يلزم تسجيل استلام الدفع من الإدارة قبل السماح بالصعود.'}<br/>الشركة غير مسؤولة عن أي أغراض تُترك داخل الحافلة.</p></article>)}</div></section><BookingJourney key={booking.code+booking.trackingToken} booking={booking} stations={stations}/><BookingSummaryDownload booking={booking} stations={stations}/></>}
