'use client';
import {useLocale} from '@/lib/arkan-client';
export default function BookingPaymentOptions({payments,hold,count,busy,onChange}:{payments:any;hold:any;count:number;busy:boolean;onChange:(value:string)=>void}){
 const {t}=useLocale(),selected=hold.paymentMethod||'cash',available=hold.sponsored?.available||0;
 return <div className="payment-options" role="radiogroup" aria-label={t('طريقة الدفع','Payment method')}>
  {payments?.cash&&<label className={'payment-option payment-choice '+(selected==='cash'?'selected':'')}><input type="radio" name="paymentMethod" value="cash" checked={selected==='cash'} disabled={busy} onChange={()=>onChange('cash')}/><span><strong>{t('الدفع نقدًا (كاش)','Cash payment')}</strong><p>{t('ادفع نقدًا للموظف المخوّل. تُحدّث الإدارة حالة الحجز بعد استلام المبلغ.','Pay cash to an authorized staff member. Administration confirms payment once received.')}</p></span></label>}
  {available>0&&<label className={'payment-option payment-choice sponsored-choice '+(selected==='sponsored'?'selected':'')}><input type="radio" name="paymentMethod" value="sponsored" checked={selected==='sponsored'} disabled={busy||available<count} onChange={()=>onChange('sponsored')}/><span><span className="tag">{t('ضيافة فاعل خير','Sponsored by a donor')}</span><strong>{t('مقعد مجاني لغير القادر على الدفع','Free seat for those unable to pay')}</strong><p>{t('يغطي التبرع قيمة النقل بالكامل، دون دفع من المسافر.','The donation covers the full transport fare at no charge to the passenger.')}</p><small>{available<count?t('المتاح لا يكفي لجميع المسافرين في هذا الحجز. احجز المستفيدين في حجز مستقل.','Not enough sponsored seats for everyone. Make a separate booking for the beneficiaries.'):t('متاح للحجز الحالي، بما فيه العودة إن وُجدت. يُحسم التوفر عند تأكيد الحجز.','Available for this booking, including the return leg if selected. Availability is secured on confirmation.')}</small></span></label>}
  {payments?.showOnline&&<div className="payment-option upcoming" aria-disabled="true"><span className="tag">{t('قريبًا','Coming soon')}</span><h3>{t('الدفع الإلكتروني — خصم ٥٪','Online payment — 5% off')}</h3><p dir="ltr">Mada · Apple Pay · Visa · Mastercard</p><small>{t('سيُطبق الخصم عند إتاحة الدفع الإلكتروني. لا يشمل الدفع الكاش.','Discount applies when online payment launches. Cash payments are excluded.')}</small></div>}
  {!payments?.cash&&available<count&&<p className="error" role="alert">{t('الدفع غير متاح حاليًا. تواصل مع الإدارة لإتمام الحجز.','Payment is currently unavailable. Contact support.')}</p>}
 </div>;
}
