'use client';
import {useEffect,useRef,useState} from 'react';
import {api,errorMessage,useLocale} from '@/lib/arkan-client';
export default function SponsoredSeatsDialog({trip,onClose,onSaved}:{trip:any;onClose:()=>void;onSaved:()=>Promise<void>}){
 const {en,t}=useLocale(),ref=useRef<HTMLDialogElement>(null),requestId=useRef(crypto.randomUUID()),lock=useRef(false);
 const [data,setData]=useState<any>(null),[seats,setSeats]=useState(''),[funded,setFunded]=useState(false),[busy,setBusy]=useState(false),[attempted,setAttempted]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const dialog=ref.current;dialog?.showModal();let live=true;api('sponsoredSeats&trip='+encodeURIComponent(trip.id)).then(v=>{if(live){setData(v);setSeats(String(v.seats))}}).catch(e=>{if(live)setError(errorMessage(e,en))});return()=>{live=false;dialog?.close()}},[trip.id]);
 async function save(e:React.FormEvent){e.preventDefault();if(lock.current||!data)return;lock.current=true;setBusy(true);setAttempted(true);setError('');try{await api('saveSponsoredSeats',{trip:trip.id,seats:Number(seats),expectedRevision:data.revision,requestId:requestId.current,funded});await onSaved();onClose()}catch(e){setError(errorMessage(e,en))}finally{lock.current=false;setBusy(false)}}
 return <dialog ref={ref} className="sponsored-dialog" onCancel={e=>{e.preventDefault();if(!busy)onClose()}} aria-labelledby="sponsored-title"><form onSubmit={save}><h2 id="sponsored-title">{t('مقاعد مجانية — ضيافة فاعل خير','Free seats — donor sponsorship')}</h2><p dir="ltr">{trip.date} · {trip.time}</p><p>{t('تظهر للعميل ضمن طريقة الدفع عند توفر الحصة. اضبط العدد بعد تغطية التبرع لدى الشركة.','Shown as a payment option while an allowance remains. Set the allowance after the company receives sponsorship.')}</p>{data?<><p>{t('المستخدم: ','Used: ')}{data.used} · {t('المتبقي: ','Remaining: ')}{data.available}</p><fieldset disabled={busy||attempted}><label>{t('إجمالي المقاعد المتبرع بها لهذه الرحلة','Total funded seats for this trip')}<input type="number" required min={data.used} max={trip.capacity} step="1" value={seats} onChange={e=>setSeats(e.target.value)}/></label><p className="muted">{t('لإيقاف إتاحة مقاعد جديدة، اجعل الإجمالي مساويًا للمستخدم. الحجوزات المؤكدة تبقى محفوظة.','To stop new sponsored bookings, set the total to the used count. Confirmed bookings remain valid.')}</p><label className="sponsored-funded"><input type="checkbox" checked={funded} required onChange={e=>setFunded(e.target.checked)}/>{t('أؤكد أن العدد مدعوم بتبرع مُغطّى لدى الشركة، أو أنني أخفّض الحصة المتاحة.','I confirm the allowance is funded, or that I am reducing the available allowance.')}</label></fieldset></>:<p>{t('جارٍ التحميل…','Loading…')}</p>}{error&&<p className="ops-error" role="alert">{error}</p>}<div className="ledger-actions"><button type="submit" className="primary" disabled={busy||!data||!funded}>{busy?t('جارٍ الحفظ…','Saving…'):attempted?t('إعادة المحاولة','Retry'):t('حفظ المقاعد المجانية','Save free seats')}</button><button type="button" className="secondary" disabled={busy} onClick={onClose}>{t('إغلاق','Close')}</button></div></form></dialog>;
}
