import {packageSchema,packageVisible,sortPackages} from './travel-packages';
import {paymentPolicy} from './payment-policy';
import { env } from 'cloudflare:workers';
import {staffUser,requireStaff,saveAccount,removeAccount} from './operations-auth';
import {issueBookingAccess} from './trip-operations';
import { z } from 'zod';
import {seedRequestedCheckinTrial} from './checkin-trial';
import {TRIAL_BOOKING,TRIAL_TICKET,TRIAL_TRIP,TRIAL_DRIVER} from './checkin-trial-config';
export function db(){if(!env.DB)throw new Error('DATABASE_UNAVAILABLE');return env.DB}
export const now=()=>Date.now();
export const today=()=>new Date(Date.now()+10800000).toISOString().slice(0,10);
export function fail(code:string,status=400):never{throw Object.assign(new Error(code),{status})}
const id=()=>crypto.randomUUID();
const str=z.string().trim().min(1).max(180);
const dateSchema=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(x=>!isNaN(Date.parse(x))&&new Date(x+'T00:00:00Z').toISOString().slice(0,10)===x);
const timeSchema=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
export const mobile=(s:string)=>s.replace(/[^\d]/g,'').replace(/^00966/,'966').replace(/^05/,'9665');
export async function seed(){await seedRequestedCheckinTrial(db());if(await db().prepare("SELECT key FROM settings WHERE key='initialized'").first())return;
const entities=[['jeddah','station',{ar:'جدة — المحطة الرئيسية',en:'Jeddah — Central station',city:'jeddah',active:true}],['makkah','station',{ar:'مكة — محطة العزيزية',en:'Makkah — Al Aziziyah',city:'makkah',active:true}],['bus-1','bus',{plate:'DEMO 01',seats:49}],['bus-2','bus',{plate:'DEMO 02',seats:49}],...['07:30','16:30'].flatMap((time,i)=>['jeddah','makkah'].map((from,j)=>[`schedule-${i}-${j}`,'schedule',{from,to:from==='jeddah'?'makkah':'jeddah',time,bus:j?'bus-2':'bus-1',driver:'',start:'2026-01-01',end:'2099-12-31',active:true}]))];
await db().batch([...entities.map(([key,kind,data])=>db().prepare("INSERT OR IGNORE INTO entities(id,kind,data) VALUES(?,?,?)").bind(key,kind,JSON.stringify(data))),...Object.entries({one:15,round:30,whatsapp:'',contactEmail:'',cancellationAr:cancellationCopy.ar,cancellationEn:cancellationCopy.en}).map(([k,v])=>db().prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').bind(k,JSON.stringify(v))),db().prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('initialized','true')")]);}
const cancellationCopy={ar:'لإلغاء طلب الحجز، يُرجى تزويد خدمة العملاء برقم الحجز ورقم الجوال المسجل. لا يترتب على إلغاء طلب لم يُدفع أي استرداد مالي. تُعرض شروط الإلغاء والاسترداد للحجوزات المدفوعة عند إتاحة الدفع وقبل إتمامه.',en:'To cancel a booking request, provide customer support with your booking number and registered mobile number. No refund applies to an unpaid request. Cancellation and refund terms for paid bookings will be shown before payment when online payment becomes available.'};
const legacyCancellation={ar:'سياسة الإلغاء والاسترداد قيد الاعتماد. هذه نسخة تجريبية؛ لا تُحصَّل أي مبالغ ولا تُصدر تذاكر سفر فعلية.',en:'Cancellation and refund terms are awaiting approval. This is a demo: no payments are collected and no travel-valid tickets are issued.'};
export async function settings(){const cfg=Object.fromEntries((await db().prepare('SELECT * FROM settings').all<any>()).results.map(x=>[x.key,JSON.parse(x.value)]));if(cfg.cancellationAr===legacyCancellation.ar)cfg.cancellationAr=cancellationCopy.ar;if(cfg.cancellationEn===legacyCancellation.en)cfg.cancellationEn=cancellationCopy.en;cfg.paymentMode=paymentPolicy(cfg).mode;return cfg}
export async function entities(kind?:string){const r=await (kind?db().prepare('SELECT * FROM entities WHERE kind=?').bind(kind):db().prepare("SELECT * FROM entities WHERE kind<>'booking_metadata'")).all<any>();return r.results.map(x=>{const data=JSON.parse(x.data);if(x.kind==='bus'&&/^DEMO \d+$/.test(data.plate||''))data.plate='';return{id:x.id,kind:x.kind,...data}})}
export const role=staffUser;
export async function authorized(admin=false){return requireStaff(admin?['admin']:['admin','checkin'])}
export async function rateLimit(req:Request,action:string,max=35){const ip=req.headers.get('cf-connecting-ip')||'anonymous';const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ip));const key=action+':'+Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,'0')).join('')+':'+Math.floor(now()/900000);const row=await db().prepare('INSERT INTO limits(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,now()+900000).first<any>();if(row.count>max)fail('RATE_LIMITED',429);await db().prepare('DELETE FROM limits WHERE expires<?').bind(now()).run();}
export async function materialize(date:string){dateSchema.parse(date);const start=Date.parse(date+'T00:00:00+03:00');if(start>now()+90*86400000)fail('DATE_RANGE');if(date<today())return;const schedules=await entities('schedule');const statements=schedules.filter(s=>s.active&&date>=s.start&&date<=s.end).map(s=>db().prepare('INSERT OR IGNORE INTO trips(id,date,time,starts,from_station,to_station,bus,driver,status) VALUES(?,?,?,?,?,?,?,?,\'active\')').bind(s.id+'_'+date,date,s.time,Date.parse(date+'T'+s.time+':00+03:00'),s.from,s.to,s.bus,s.driver||''));if(statements.length)await db().batch(statements);}
export async function tripList(date:string,from?:string,to?:string){await materialize(date);let sql="SELECT t.*,COALESCE(p.phase,'scheduled') phase,p.updated,49-(SELECT count(*) FROM holds h WHERE h.trip_id=t.id AND (h.status='booked' OR h.expires>?)) available FROM trips t LEFT JOIN trip_progress p ON p.trip_id=t.id WHERE date=?";const args:any[]=[now(),date];if(from&&to){sql+=" AND from_station=? AND to_station=? AND t.status='active' AND COALESCE(p.phase,'scheduled') IN ('scheduled','boarding') AND starts>?";args.push(from,to,now())}return(await db().prepare(sql+' ORDER BY starts').bind(...args).all<any>()).results}
export async function seats(trip:string){return(await db().prepare("SELECT seat,status FROM holds WHERE trip_id=? AND (status='booked' OR expires>?)").bind(trip,now()).all()).results}
const legSchema=z.object({trip:str,seats:z.array(z.number().int().min(1).max(49)).min(1).max(49)});
export async function makeHold(body:any,req:Request){await rateLimit(req,'hold',30);if(!paymentPolicy(await settings()).cash)fail('PAYMENT_METHOD_UNAVAILABLE',409);const b=z.object({legs:z.array(legSchema).min(1).max(2)}).parse(body);const n=b.legs[0].seats.length;if(b.legs.some(l=>new Set(l.seats).size!==n||l.seats.length!==n))fail('SEAT_COUNT');if(b.legs.length===2&&b.legs[0].trip===b.legs[1].trip)fail('INVALID_RETURN');const ts=await Promise.all(b.legs.map(l=>db().prepare("SELECT * FROM trips WHERE id=? AND status='active' AND starts>? AND NOT EXISTS(SELECT 1 FROM trip_progress p WHERE p.trip_id=trips.id AND p.phase IN ('in_transit','arrived'))").bind(l.trip,now()).first<any>()));if(ts.some(t=>!t))fail('TRIP_UNAVAILABLE');if(ts.length===2&&(ts[0].from_station!==ts[1].to_station||ts[0].to_station!==ts[1].from_station||ts[1].starts<ts[0].starts+90*60000))fail('INVALID_RETURN');const token=id()+id(),expires=now()+600000;const cfg=await settings();const amount=Math.round(Number(ts.length===2?cfg.round:cfg.one)*100)*n;const statements=[db().prepare("DELETE FROM holds WHERE status='held' AND expires<=?").bind(now()),db().prepare('INSERT INTO hold_groups(token,expires,amount,expected,intent) VALUES(?,?,?,?,?)').bind(token,expires,amount,n*ts.length,JSON.stringify(b.legs)),...b.legs.flatMap(l=>l.seats.map(s=>db().prepare("INSERT INTO holds(trip_id,seat,token,expires,status) VALUES((SELECT id FROM trips WHERE id=? AND status='active' AND starts>? AND NOT EXISTS(SELECT 1 FROM trip_progress p WHERE p.trip_id=trips.id AND p.phase IN ('in_transit','arrived'))),?,?,?,'held')").bind(l.trip,now(),s,token,expires)))];try{await db().batch(statements)}catch{fail('SEAT_TAKEN',409)}return{token,expires,amount};}
async function bookingMetadata(code:string){const row=await db().prepare("SELECT data FROM entities WHERE id=? AND kind='booking_metadata'").bind('booking:'+code).first<any>();return row?JSON.parse(row.data):{passengers:{},paymentEvents:[]}}
async function bookingResult(code:string,access=false){const metadata=await bookingMetadata(code);const identities=new Map<string,number>();const b=await db().prepare('SELECT code,mobile,email,amount,status,created,refund FROM bookings WHERE code=?').bind(code).first<any>();const t=(await db().prepare("SELECT k.id,k.trip_id,k.name,k.national_id,k.nationality,k.seat,k.boarded,t.date,t.time,t.from_station,t.to_station,t.bus,(SELECT json_extract(e.data,'$.plate') FROM entities e WHERE e.id=t.bus) bus_plate,t.status trip_status FROM tickets k JOIN trips t ON t.id=k.trip_id WHERE booking_code=? ORDER BY t.starts,k.seat").bind(code).all<any>()).results.map(({national_id,...x})=>{const identity=JSON.stringify([x.name,national_id,x.nationality]);if(!identities.has(identity))identities.set(identity,identities.size);return({...x,passengerIndex:identities.get(identity),...metadata.passengers?.[x.id],bus_plate:/^DEMO \d+$/.test(x.bus_plate||'')?'':x.bus_plate,maskedId:national_id?'****'+national_id.slice(-4):'—'})});return{...b,paymentMethod:metadata.paymentMethod||null,tickets:t,...(access?{trackingToken:await issueBookingAccess(code)}:{}),delivery:{email:'not_configured',whatsapp:'not_configured'}}}
export async function confirm(body:any,req:Request){await rateLimit(req,'confirm');const b=z.object({token:z.string().min(64).max(100),passengers:z.array(z.object({name:str.refine(x=>x.length>=3),title:z.enum(['mr','mrs','child']),identityType:z.enum(['national_id','iqama','passport']),nationalId:z.string().trim().transform(x=>x.replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).toUpperCase()),nationality:str}).refine(p=>p.identityType==='passport'?/^[A-Z0-9-]{3,20}$/.test(p.nationalId):/^\d{10}$/.test(p.nationalId))).min(1).max(49),mobile:z.string().transform(mobile).refine(x=>/^9665\d{8}$/.test(x)),email:z.string().trim().email().max(180),accept:z.literal(true),paymentMethod:z.literal('cash')}).parse(body);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify({passengers:b.passengers,mobile:b.mobile,email:b.email}))))).map(n=>n.toString(16).padStart(2,'0')).join('');const previous=await db().prepare('SELECT code,mobile,email,request_hash FROM bookings WHERE hold_token=?').bind(b.token).first<any>();if(previous){if(previous.mobile!==b.mobile||previous.email!==b.email||previous.request_hash!==hash)fail('CONFLICT',409);return bookingResult(previous.code,true)}
if(!paymentPolicy(await settings()).cash)fail('PAYMENT_METHOD_UNAVAILABLE',409);
const group=await db().prepare('SELECT * FROM hold_groups WHERE token=? AND expires>?').bind(b.token,now()).first<any>();if(!group)fail('HOLD_EXPIRED',409);const held=(await db().prepare("SELECT h.*,t.from_station,t.to_station,t.starts FROM holds h JOIN trips t ON t.id=h.trip_id WHERE token=? AND h.status='held' AND expires>? AND t.status='active' AND t.starts>? AND NOT EXISTS(SELECT 1 FROM trip_progress p WHERE p.trip_id=t.id AND p.phase IN ('in_transit','arrived')) ORDER BY t.starts,h.seat").bind(b.token,now(),now()).all<any>()).results;const tripIds=[...new Set(held.map(h=>h.trip_id))];if(held.length!==group.expected||tripIds.length!==JSON.parse(group.intent).length||tripIds.length<1||tripIds.length>2||held.length!==b.passengers.length*tripIds.length||tripIds.some(t=>held.filter(h=>h.trip_id===t).length!==b.passengers.length))fail('HOLD_EXPIRED',409);const amount=group.amount,code='AM-'+crypto.randomUUID().replace(/-/g,'').slice(0,12).toUpperCase(),at=now();
const passengerMetadata:Record<string,any>={};const ticketStatements=JSON.parse(group.intent).flatMap((leg:any)=>leg.seats.map((seat:number,i:number)=>{const ticketId=id()+id();const passenger=b.passengers[i];passengerMetadata[ticketId]={title:passenger.title,identityType:passenger.identityType,passengerIndex:i};return db().prepare('INSERT INTO tickets(id,booking_code,trip_id,seat,name,national_id,nationality) VALUES(?,?,?,?,?,?,?)').bind(ticketId,code,leg.trip,seat,passenger.name,passenger.nationalId,passenger.nationality)}));
const statements=[db().prepare("INSERT INTO bookings(code,hold_token,request_hash,mobile,email,amount,status,created,refund) SELECT ?,?,?,?,?,?,'pending',?,'none' WHERE COALESCE((SELECT value FROM settings WHERE key='paymentMode'),'\"both\"') IN ('\"cash\"','\"both\"') AND (SELECT COUNT(*) FROM holds h JOIN trips t ON t.id=h.trip_id WHERE h.token=? AND h.status='held' AND h.expires>? AND t.status='active' AND t.starts>? AND NOT EXISTS(SELECT 1 FROM trip_progress p WHERE p.trip_id=t.id AND p.phase IN ('in_transit','arrived')))=?").bind(code,b.token,hash,b.mobile,b.email,amount,at,b.token,at,at,held.length),...ticketStatements,db().prepare("INSERT INTO entities(id,kind,data) VALUES(?,'booking_metadata',?)").bind('booking:'+code,JSON.stringify({paymentMethod:'cash',passengers:passengerMetadata,paymentEvents:[]})),db().prepare("UPDATE holds SET status='booked' WHERE token=? AND EXISTS(SELECT 1 FROM bookings WHERE code=?)").bind(b.token,code)];try{await db().batch(statements)}catch{const concurrent=await db().prepare('SELECT code,mobile,email,request_hash FROM bookings WHERE hold_token=?').bind(b.token).first<any>();if(concurrent&&concurrent.mobile===b.mobile&&concurrent.email===b.email&&concurrent.request_hash===hash)return bookingResult(concurrent.code,true);fail('HOLD_EXPIRED',409)}return bookingResult(code,true);}
export async function lookup(body:any,req:Request){await rateLimit(req,'lookup',20);const code=str.parse(body.code).toUpperCase(),phone=mobile(str.parse(body.mobile));const row=await db().prepare('SELECT code FROM bookings WHERE code=? AND mobile=?').bind(code,phone).first<any>();if(!row)fail('BOOKING_NOT_FOUND',404);return bookingResult(row.code,true)}
export async function adminState(date:string){
const u=await authorized();await materialize(date);
const [es,ts,cfg]=await Promise.all([entities(),tripList(date),settings()]);
const manifest=(await db().prepare('SELECT k.id,k.booking_code,k.trip_id,k.name,k.national_id,k.nationality,k.seat,k.boarded,k.staff,b.status FROM tickets k JOIN bookings b ON b.code=k.booking_code JOIN trips t ON t.id=k.trip_id WHERE t.date=? ORDER BY t.starts,k.seat').bind(date).all<any>()).results;
const user={name:u.displayName||u.email,email:u.email,role:u.role};
if(u.role!=='admin')return{user,trips:ts,manifest,entities:es.filter(e=>e.kind==='station'||e.kind==='bus'||(e.kind==='driver'&&ts.some(t=>t.driver===e.id))).map(({mobile,...e})=>e),settings:null,staff:[],reports:null};
const start=Date.parse(date+'T00:00:00+03:00');
const reports=await db().prepare("SELECT count(*) count,COALESCE(sum(CASE WHEN status IN ('demo','pending') THEN amount ELSE 0 END),0) demoTotal,COALESCE(sum(CASE WHEN status='paid' THEN amount ELSE 0 END),0) sales,COALESCE(sum(CASE WHEN status IN ('demo','pending') THEN 1 ELSE 0 END),0) pending,COALESCE(sum(CASE WHEN status='paid' THEN 1 ELSE 0 END),0) paid,COALESCE(sum(CASE WHEN status='cancelled' THEN 1 ELSE 0 END),0) cancelled FROM bookings WHERE created>=? AND created<? AND code<>?").bind(start,start+86400000,TRIAL_BOOKING).first<any>();
return{user,entities:es,trips:ts,manifest,settings:cfg,staff:(await db().prepare('SELECT id,email,name,role,driver_id,must_change,active FROM accounts ORDER BY email').all()).results,reports};
}
export async function adminBooking(code:string){
await authorized(true);const key=str.parse(code).toUpperCase();const booking=await bookingResult(key);if(!booking?.code)fail('BOOKING_NOT_FOUND',404);
const passengers=(await db().prepare('SELECT k.*,t.date,t.time,t.from_station,t.to_station,t.bus,t.driver,t.status trip_status FROM tickets k JOIN trips t ON t.id=k.trip_id WHERE k.booking_code=? ORDER BY t.starts,k.seat').bind(key).all<any>()).results;
const metadata=await bookingMetadata(key);return{...booking,passengers:passengers.map(p=>({...p,...metadata.passengers?.[p.id]})),paymentEvents:metadata.paymentEvents||[]};
}
export async function adminAction(body:any){const op=body.op;const u=await requireStaff(op==='scan'?['admin','checkin','driver']:['admin']);if(op==='saveSettings'){const b=z.object({one:z.number().min(0).max(10000),round:z.number().min(0).max(10000),whatsapp:z.string().max(20).refine(v=>!v||/^9665\d{8}$/.test(mobile(v))),contactEmail:z.string().max(180).refine(x=>!x||z.string().email().safeParse(x).success),cancellationAr:z.string().min(5).max(4000),cancellationEn:z.string().min(5).max(4000),paymentMode:z.enum(['cash','online','both']).optional()}).parse(body.data);if(b.paymentMode==='online')fail('PAYMENT_GATEWAY_NOT_READY',409);await db().batch(Object.entries(b).filter(([,v])=>v!==undefined).map(([k,v])=>db().prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(k,JSON.stringify(k==='whatsapp'?mobile(String(v)):v))));return{ok:true}}
if(op==='savePackage'){const d=packageSchema.parse(body.data);const key=body.id?str.parse(body.id):'package-'+id();const result=await db().prepare("INSERT INTO entities(id,kind,data) VALUES(?,'package',?) ON CONFLICT(id) DO UPDATE SET data=excluded.data WHERE entities.kind='package'").bind(key,JSON.stringify(d)).run();if(!result.meta.changes)fail('CONFLICT',409);return{ok:true,id:key}}
if(op==='saveEntity'){const kind=z.enum(['station','bus','driver','schedule']).parse(body.kind);let d:any;switch(kind){case 'station':d=z.object({ar:str,en:str,city:z.enum(['jeddah','makkah']),active:z.boolean()}).parse(body.data);break;case 'bus':d=z.object({plate:str,seats:z.literal(49)}).parse(body.data);break;case 'driver':d=z.object({name:str,nationalId:z.string().regex(/^\d{10}$/),mobile:z.string().transform(mobile).refine(x=>/^9665\d{8}$/.test(x))}).parse(body.data);break;case 'schedule':d=z.object({from:str,to:str,time:timeSchema,bus:str,driver:z.string().max(180),start:dateSchema,end:dateSchema,active:z.boolean()}).parse(body.data);if(d.from===d.to||d.start>d.end)fail('INVALID_ROUTE');if(d.active){await validateAssignment(d);await ensureDepartureAvailable(d,body.id||'',true)}break}const key=body.id?str.parse(body.id):id();await db().prepare('INSERT INTO entities(id,kind,data) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data WHERE entities.kind=excluded.kind').bind(key,kind,JSON.stringify(d)).run();return{ok:true,id:key}}
if(op==='saveTrip'){const d=z.object({date:dateSchema,time:timeSchema,from:str,to:str,bus:str,driver:z.string().max(180)}).parse(body.data);await validateAssignment(d);const starts=Date.parse(d.date+'T'+d.time+':00+03:00');if(starts<=now()||d.from===d.to)fail('INVALID_ROUTE');await materialize(d.date);await ensureDepartureAvailable(d,body.id||'');const key=body.id?str.parse(body.id):id();const r=await db().prepare("INSERT INTO trips(id,date,time,starts,from_station,to_station,bus,driver,status) VALUES(?,?,?,?,?,?,?,?,'active') ON CONFLICT(id) DO UPDATE SET date=excluded.date,time=excluded.time,starts=excluded.starts,from_station=excluded.from_station,to_station=excluded.to_station,bus=excluded.bus,driver=excluded.driver WHERE trips.status='active' AND NOT EXISTS(SELECT 1 FROM trip_progress p WHERE p.trip_id=trips.id AND p.phase IN ('in_transit','arrived')) AND (NOT EXISTS(SELECT 1 FROM holds WHERE trip_id=? AND (status='booked' OR expires>?)) OR (trips.date=excluded.date AND trips.time=excluded.time AND trips.from_station=excluded.from_station AND trips.to_station=excluded.to_station AND trips.bus=excluded.bus))").bind(key,d.date,d.time,starts,d.from,d.to,d.bus,d.driver,key,now()).run();if(!r.meta.changes)fail('TRIP_HAS_BOOKINGS',409);return{ok:true}}
if(op==='setPaymentStatus'){
const b=z.object({code:str,expectedStatus:z.enum(['demo','pending','paid']),status:z.enum(['pending','paid'])}).parse(body);
if(b.status===b.expectedStatus)return{ok:true};
const metadata=await bookingMetadata(b.code),eventId=id();
const event={id:eventId,from:b.expectedStatus,to:b.status,at:now(),actor:u.email};
const guard="code=? AND status=? AND NOT EXISTS(SELECT 1 FROM tickets k WHERE k.booking_code=bookings.code AND k.boarded IS NOT NULL) AND EXISTS(SELECT 1 FROM tickets k WHERE k.booking_code=bookings.code) AND NOT EXISTS(SELECT 1 FROM tickets k JOIN trips t ON t.id=k.trip_id WHERE k.booking_code=bookings.code AND (t.status<>'active' OR NOT EXISTS(SELECT 1 FROM holds h WHERE h.trip_id=k.trip_id AND h.seat=k.seat AND h.token=bookings.hold_token AND h.status='booked')))";
const result=await db().batch([
db().prepare("INSERT INTO entities(id,kind,data) SELECT ?,'booking_metadata',? WHERE EXISTS(SELECT 1 FROM bookings WHERE "+guard+") AND NOT EXISTS(SELECT 1 FROM entities WHERE id=? AND data<>?) ON CONFLICT(id) DO UPDATE SET data=excluded.data WHERE entities.kind='booking_metadata'").bind('booking:'+b.code,JSON.stringify({...metadata,paymentMethod:'cash',paymentEvents:[...(metadata.paymentEvents||[]),event]}),b.code,b.expectedStatus,'booking:'+b.code,JSON.stringify(metadata)),
db().prepare("UPDATE bookings SET status=? WHERE "+guard+" AND EXISTS(SELECT 1 FROM entities WHERE id=? AND json_extract(data,'$.paymentEvents[#-1].id')=?)").bind(b.status,b.code,b.expectedStatus,'booking:'+b.code,eventId)
]);if(!result[1].meta.changes)fail('PAYMENT_LOCKED',409);return{ok:true}}
if(op==='cancelBooking'){const code=str.parse(body.code);const booking=await db().prepare('SELECT status FROM bookings WHERE code=?').bind(code).first<any>();if(!booking)fail('BOOKING_NOT_FOUND',404);if(booking.status==='paid')fail('REFUND_NOT_CONFIGURED',409);await cancelBooking(code);return{ok:true}}
if(op==='cancelTrip'){const trip=str.parse(body.id);if(await db().prepare("SELECT trip_id FROM trip_progress WHERE trip_id=? AND phase IN ('in_transit','arrived')").bind(trip).first())fail('INVALID_TRANSITION',409);if(!await db().prepare('SELECT id FROM trips WHERE id=?').bind(trip).first())fail('TRIP_NOT_FOUND',404);if(await db().prepare("SELECT b.code FROM bookings b JOIN tickets k ON k.booking_code=b.code WHERE k.trip_id=? AND b.status='paid' LIMIT 1").bind(trip).first())fail('REFUND_NOT_CONFIGURED',409);const cancelled=await db().batch([db().prepare("UPDATE trips SET status='cancelled' WHERE id=? AND NOT EXISTS(SELECT 1 FROM trip_progress p WHERE p.trip_id=trips.id AND p.phase IN ('in_transit','arrived')) AND NOT EXISTS(SELECT 1 FROM tickets k JOIN bookings b ON b.code=k.booking_code WHERE k.trip_id=trips.id AND b.status='paid')").bind(trip),db().prepare("UPDATE bookings SET status='cancelled',refund='not_charged' WHERE status IN ('demo','pending','test') AND code IN (SELECT k.booking_code FROM tickets k JOIN trips t ON t.id=k.trip_id WHERE k.trip_id=? AND t.status='cancelled')").bind(trip),db().prepare("DELETE FROM holds WHERE (trip_id=? AND EXISTS(SELECT 1 FROM trips WHERE id=? AND status='cancelled')) OR token IN (SELECT hold_token FROM bookings WHERE status='cancelled')").bind(trip,trip)]);if(!cancelled[0].meta.changes)fail('INVALID_TRANSITION',409);return{ok:true}}
if(op==='staff')return body.role==='remove'?removeAccount(body.email):saveAccount(body);
if(op==='scan'){const token=str.parse(body.token),trip=str.parse(body.trip);const target=await db().prepare("SELECT t.driver,COALESCE(p.phase,'scheduled') phase FROM trips t LEFT JOIN trip_progress p ON p.trip_id=t.id WHERE t.id=?").bind(trip).first<any>();if(u.role==='driver'&&(!target||target.driver!==u.driverId))fail('FORBIDDEN',403);if(target?.phase==='in_transit'||target?.phase==='arrived')return{status:'BOARDING_CLOSED'};const t=await db().prepare('SELECT k.*,b.status,t.status trip_status,t.date,t.time FROM tickets k JOIN bookings b ON b.code=k.booking_code JOIN trips t ON t.id=k.trip_id WHERE k.id=?').bind(token).first<any>();if(!t||t.status==='cancelled'||t.trip_status!=='active')return{status:'INVALID'};if(t.trip_id!==trip)return{status:'WRONG_TRIP'};const trial=t.status==='test'&&t.booking_code===TRIAL_BOOKING&&t.id===TRIAL_TICKET&&t.trip_id===TRIAL_TRIP&&target?.driver===TRIAL_DRIVER;if(t.status!=='paid'&&!trial)return{status:'PAYMENT_PENDING',name:t.name,seat:t.seat,date:t.date,time:t.time};if(t.boarded)return{status:'ALREADY_USED',name:t.name,seat:t.seat,boarded:t.boarded};const r=await db().prepare("UPDATE tickets SET boarded=?,staff=? WHERE id=? AND boarded IS NULL AND EXISTS(SELECT 1 FROM bookings b JOIN trips t ON t.id=tickets.trip_id WHERE b.code=tickets.booking_code AND (b.status='paid' OR (b.status='test' AND b.code=? AND tickets.id=? AND t.id=? AND t.driver=?)) AND t.status='active' AND NOT EXISTS(SELECT 1 FROM trip_progress p WHERE p.trip_id=t.id AND p.phase IN ('in_transit','arrived')) AND (?='admin' OR ?='checkin' OR t.driver=?)) RETURNING name,seat,boarded").bind(now(),u.email,token,TRIAL_BOOKING,TRIAL_TICKET,TRIAL_TRIP,TRIAL_DRIVER,u.role,u.role,u.driverId).first<any>();if(r)return{status:'VALID',...r,date:t.date,time:t.time,test:trial};const latest=await db().prepare('SELECT boarded FROM tickets WHERE id=?').bind(token).first<any>();return latest?.boarded?{status:'ALREADY_USED',name:t.name,seat:t.seat,boarded:latest.boarded}:{status:'INVALID'}}fail('UNKNOWN_ACTION')}
async function ensureDepartureAvailable(d:any,excludeId:string,recurring=false){
const start=recurring?d.start:d.date,end=recurring?d.end:d.date;
const trips=(await db().prepare("SELECT id,bus,driver FROM trips WHERE status='active' AND date>=? AND date<=? AND time=? AND id<>? AND (bus=? OR (?<>'' AND driver=?))").bind(start,end,d.time,excludeId,d.bus,d.driver,d.driver).all<any>()).results;
if(trips.some(tr=>!recurring||!tr.id.startsWith(excludeId+'_')))fail('ASSIGNMENT_CONFLICT',409);
const schedules=await entities('schedule');
if(schedules.some(s=>s.active&&s.id!==excludeId&&(recurring||excludeId!==s.id+'_'+d.date)&&s.time===d.time&&s.start<=end&&s.end>=start&&(s.bus===d.bus||(d.driver&&s.driver===d.driver))))fail('ASSIGNMENT_CONFLICT',409);
}
async function validateAssignment(d:any){const es=await entities();const from=es.find(e=>e.id===d.from&&e.kind==='station'&&e.active),to=es.find(e=>e.id===d.to&&e.kind==='station'&&e.active);if(!from||!to||from.city===to.city||!es.some(e=>e.id===d.bus&&e.kind==='bus')||(d.driver&&!es.some(e=>e.id===d.driver&&e.kind==='driver')))fail('INVALID_ROUTE')}
async function cancelBooking(code:string){await db().batch([db().prepare("UPDATE bookings SET status='cancelled',refund='not_charged' WHERE code=? AND status IN ('demo','pending','test')").bind(code),db().prepare("DELETE FROM holds WHERE token IN (SELECT hold_token FROM bookings WHERE code=? AND status='cancelled')").bind(code)])}
export async function adminSearch(query:string,status='',date=''){
await authorized(true);const term=query.trim().slice(0,100);const normalized=/^(05|9665|\+9665|009665)/.test(term)?mobile(term):term;const q='%'+term+'%',phone='%'+normalized+'%';
let sql='SELECT b.code,b.mobile,b.email,b.amount,b.status,b.created,b.refund,(SELECT count(*) FROM tickets t WHERE t.booking_code=b.code) ticket_count FROM bookings b WHERE (b.code LIKE ? OR b.mobile LIKE ? OR EXISTS(SELECT 1 FROM tickets t WHERE t.booking_code=b.code AND (t.national_id LIKE ? OR t.name LIKE ?)))';const args:any[]=[q,phone,q,q];
if(status){z.enum(['demo','pending','paid','cancelled','test']).parse(status);if(status==='pending'||status==='demo')sql+=" AND b.status IN ('pending','demo')";else{sql+=' AND b.status=?';args.push(status)}}
if(date){dateSchema.parse(date);const start=Date.parse(date+'T00:00:00+03:00');sql+=' AND b.created>=? AND b.created<?';args.push(start,start+86400000)}
return(await db().prepare(sql+' ORDER BY b.created DESC LIMIT 100').bind(...args).all()).results;
}

export async function publicPackages(){return sortPackages((await entities('package')).filter(p=>packageVisible(p,today())))}
