import {env} from 'cloudflare:workers';
import {headers} from 'next/headers';
import {z} from 'zod';
import {scrypt,timingSafeEqual} from 'node:crypto';
const database=()=>env.DB!;
function error(code:string,status=400):never{throw Object.assign(new Error(code),{status})}
const enc=new TextEncoder();
const hex=(bytes:ArrayBuffer|Uint8Array)=>Array.from(new Uint8Array(bytes)).map(n=>n.toString(16).padStart(2,'0')).join('');
export const digest=async(value:string)=>hex(await crypto.subtle.digest('SHA-256',enc.encode(value)));
export const randomToken=()=>hex(crypto.getRandomValues(new Uint8Array(32)));
const SESSION='__Host-arkan_staff';
const emailSchema=z.string().trim().email().max(180).transform(v=>v.toLowerCase());
const passwordSchema=z.string().min(12).max(128);
export type StaffUser={id:string;email:string;displayName:string;role:string;driverId:string;mustChange:boolean};
const derive=(password:string,salt:Uint8Array)=>new Promise<Buffer>((resolve,reject)=>scrypt(password,salt,32,{N:32768,r:8,p:3,maxmem:64*1024*1024},(e,key)=>e?reject(e):resolve(key)));
export async function hashPassword(password:string){const salt=crypto.getRandomValues(new Uint8Array(24));return 'scrypt$32768$8$3$'+hex(salt)+'$'+hex(await derive(password,salt))}
export async function verifyPassword(password:string,stored:string){const [scheme,n,r,p,salt,expected]=stored.split('$');if(scheme!=='scrypt'||n!=='32768'||r!=='8'||p!=='3'||! /^[0-9a-f]{48}$/.test(salt||'')||! /^[0-9a-f]{64}$/.test(expected||''))return false;return timingSafeEqual(await derive(password,Uint8Array.from(salt.match(/../g)!,x=>parseInt(x,16))),Uint8Array.from(expected.match(/../g)!,x=>parseInt(x,16)))}
export function cookieValue(cookie:string|null,name:string){return(cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='))?.slice(name.length+1)||''}
export async function staffUser():Promise<StaffUser|null>{const h=await headers(),token=cookieValue(h.get('cookie'),SESSION);if(!/^[0-9a-f]{64}$/.test(token))return null;const a=await database().prepare('SELECT a.id,a.email,a.name,a.role,a.driver_id,a.must_change FROM sessions s JOIN accounts a ON a.id=s.account_id WHERE s.token_hash=? AND s.expires>? AND a.active=1').bind(await digest(token),Date.now()).first<any>();return a?{id:a.id,email:a.email,displayName:a.name,role:a.role,driverId:a.driver_id,mustChange:!!a.must_change}:null}
export async function requireStaff(roles=['admin','checkin','driver'],allowChange=false):Promise<StaffUser>{const u=await staffUser();if(!u)error('UNAUTHORIZED',401);if(u.mustChange&&!allowChange)error('PASSWORD_CHANGE_REQUIRED',403);if(!roles.includes(u.role))error('FORBIDDEN',403);return u}
// Standalone Workers do not have a trusted Sites identity proxy. Owner creation
// is restricted to the operator's local provisioning command.
export async function authStatus(){const [user,configured]=await Promise.all([staffUser(),database().prepare("SELECT id FROM accounts WHERE id='owner'").first()]);return{user,canSetup:false,canRecover:false,ownerEmail:'',configured:!!configured}}
async function loginLimit(req:Request,email:string){const ip=req.headers.get('cf-connecting-ip')||'anonymous';const at=Date.now(),window=Math.floor(at/900000);for(const[key,max]of [[`auth-ip:${await digest(ip)}:${window}`,40],[`auth-email:${await digest(email)}:${window}`,10]] as const){const r=await database().prepare('INSERT INTO limits(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,at+900000).first<any>();if(r.count>max)error('RATE_LIMITED',429)}await database().prepare('DELETE FROM limits WHERE expires<?').bind(at).run()}
async function session(account:string,expectedHash:string){const token=randomToken(),expires=Date.now()+12*60*60000;const result=await database().batch([database().prepare('DELETE FROM sessions WHERE expires<?').bind(Date.now()),database().prepare('INSERT INTO sessions(token_hash,account_id,expires) SELECT ?,id,? FROM accounts WHERE id=? AND active=1 AND password_hash=?').bind(await digest(token),expires,account,expectedHash)]);if(!result[1].meta.changes)error('INVALID_CREDENTIALS',401);return `${SESSION}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`}
export async function authAction(body:any,req:Request):Promise<{data:any;cookie?:string}>{
 if(body.op==='logout'){const u=await staffUser();if(u&&typeof body.endpoint==='string')await database().prepare("DELETE FROM push_subscriptions WHERE audience='staff' AND subject=? AND json_extract(subscription,'$.endpoint')=?").bind(u.id,body.endpoint).run();const token=cookieValue(req.headers.get('cookie'),SESSION);if(token)await database().prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(token)).run();return{data:{ok:true},cookie:`${SESSION}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`}}
 if(body.op==='login'){const b=z.object({email:emailSchema,password:z.string().min(1).max(128)}).parse(body);await loginLimit(req,b.email);const a=await database().prepare('SELECT * FROM accounts WHERE email=? AND active=1').bind(b.email).first<any>();const dummy='scrypt$32768$8$3$'+'0'.repeat(48)+'$'+'0'.repeat(64);const valid=await verifyPassword(b.password,a?.password_hash||dummy);if(!a||!valid)error('INVALID_CREDENTIALS',401);return{data:{ok:true,role:a.role,mustChange:!!a.must_change},cookie:await session(a.id,a.password_hash)}}
 if(body.op==='setup'||body.op==='recover')error('FORBIDDEN',403);
 if(body.op==='changePassword'){const u=await requireStaff(undefined,true),b=z.object({currentPassword:z.string().min(1).max(128),password:passwordSchema}).parse(body);await loginLimit(req,u.email);const a=await database().prepare('SELECT password_hash FROM accounts WHERE id=?').bind(u.id).first<any>();if(!await verifyPassword(b.currentPassword,a.password_hash))error('INVALID_CREDENTIALS',401);if(b.currentPassword===b.password)error('PASSWORD_UNCHANGED');const hash=await hashPassword(b.password);const result=await database().batch([database().prepare('UPDATE accounts SET password_hash=?,must_change=0 WHERE id=? AND password_hash=? AND active=1').bind(hash,u.id,a.password_hash),database().prepare('DELETE FROM sessions WHERE account_id=? AND EXISTS(SELECT 1 FROM accounts WHERE id=? AND password_hash=?)').bind(u.id,u.id,hash)]);if(!result[0].meta.changes)error('INVALID_CREDENTIALS',401);return{data:{ok:true,role:u.role},cookie:await session(u.id,hash)}}
 error('UNKNOWN_ACTION');
}
export async function saveAccount(body:any){const u=await requireStaff(['admin']);const b=z.object({email:emailSchema,name:z.string().trim().min(2).max(100),role:z.enum(['admin','checkin','driver']),driverId:z.string().max(180).default(''),password:z.string().max(128).optional()}).parse(body);const current=await database().prepare('SELECT id FROM accounts WHERE email=?').bind(b.email).first<any>();if(current?.id==='owner'||current?.id===u.id)error('OWNER_ROLE');if(!current&&!b.password)error('PASSWORD_REQUIRED');if(b.password)passwordSchema.parse(b.password);if(b.role==='driver'&&!await database().prepare("SELECT id FROM entities WHERE id=? AND kind='driver'").bind(b.driverId).first())error('DRIVER_REQUIRED');const hash=b.password?await hashPassword(b.password):null;try{await database().batch([database().prepare('INSERT INTO accounts(id,email,name,role,driver_id,password_hash,must_change,active,created) VALUES(?,?,?,?,?,?,1,1,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,role=excluded.role,driver_id=excluded.driver_id,password_hash=COALESCE(?,accounts.password_hash),must_change=CASE WHEN ? IS NOT NULL THEN 1 ELSE accounts.must_change END,active=1').bind(current?.id||crypto.randomUUID(),b.email,b.name,b.role,b.role==='driver'?b.driverId:'',hash||'',Date.now(),hash,hash),database().prepare('DELETE FROM sessions WHERE account_id IN (SELECT id FROM accounts WHERE email=?)').bind(b.email)])}catch{error('ACCOUNT_CONFLICT',409)}return{ok:true}}
export async function removeAccount(email:string){const u=await requireStaff(['admin']);const a=await database().prepare('SELECT id FROM accounts WHERE email=?').bind(emailSchema.parse(email)).first<any>();if(!a)error('ACCOUNT_NOT_FOUND',404);if(a.id==='owner'||a.id===u.id)error('OWNER_ROLE');await database().batch([database().prepare('UPDATE accounts SET active=0 WHERE id=?').bind(a.id),database().prepare('DELETE FROM sessions WHERE account_id=?').bind(a.id)]);return{ok:true}}
