import {z} from 'zod';
import {db,settings,entities,materialize,now,today,fail,mobile,rateLimit} from './arkan-server';
import {requireStaff} from './operations-auth';
import {slotPrefix,resourceFree,slotJSON} from './resource-availability';
const text=z.string().trim().min(2).max(200),key=z.string().trim().min(1).max(180);
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v);
const time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
const stamp=(d:string,t:string)=>Date.parse(d+'T'+t+':00+03:00');
const maps=z.string().trim().url().max(1500).refine(v=>{try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password&&['maps.google.com','www.google.com','google.com','maps.app.goo.gl','goo.gl','maps.apple.com'].includes(u.hostname)}catch{return false}});
export const privateDefaults={price49:900,price24:650,price13:450,enabled:true};
export async function privateConfig(){const cfg=await settings();return {...privateDefaults,...cfg.privatePricing}}
export async function savePrivatePricing(data:any){await requireStaff(['admin']);const p=z.object({price49:z.number().min(0).max(100000),price24:z.number().min(0).max(100000),price13:z.number().min(0).max(100000),enabled:z.boolean()}).parse(data);await db().prepare("INSERT INTO settings(key,value) VALUES('privatePricing',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(p)).run();return{ok:true}}
function publicView(p:any){const{events,paymentEvents,bus,driver,...safe}=p;return safe}
export async function createPrivate(body:any,req:Request){await rateLimit(req,'private-request',12);const cfg=await privateConfig();if(!cfg.enabled)fail('TRIP_UNAVAILABLE');const p=z.object({requestId:z.string().uuid(),name:text,mobile:z.string().transform(mobile).refine(v=>/^9665\d{8}$/.test(v)),capacity:z.union([z.literal(49),z.literal(24),z.literal(13)]),passengers:z.number().int().min(1).max(49),date,time,round:z.boolean(),returnDate:date.optional(),returnTime:time.optional(),pickup:text,mapUrl:maps,destination:text,notes:z.string().trim().max(2000),accept:z.literal(true)}).parse(body);if(p.passengers>p.capacity)fail('SEAT_COUNT');const starts=stamp(p.date,p.time);if(starts<=now()||starts>now()+90*86400000)fail('DATE_RANGE');let ends=starts+5400000;if(p.round){if(!p.returnDate||!p.returnTime)fail('INVALID_RETURN');const ret=stamp(p.returnDate,p.returnTime);if(ret<ends||ret>starts+7*86400000-5400000)fail('INVALID_RETURN');ends=ret+5400000}const old=await db().prepare("SELECT data FROM entities WHERE id=? AND kind='private_booking'").bind('private:'+p.requestId).first<any>();if(old){const v=JSON.parse(old.data);if(v.mobile!==p.mobile||v.name!==p.name)fail('CONFLICT',409);return publicView(v)}const code='PV-'+crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase(),at=now();const value={...p,code,id:'private:'+p.requestId,starts,ends,estimate:Math.round(cfg[('price'+p.capacity) as keyof typeof cfg]*100)*(p.round?2:1),price:null,status:'pending',paymentStatus:'unpaid',paymentEvents:[],bus:'',driver:'',created:at,updated:at,version:1,events:[]};const result=await db().prepare("INSERT OR IGNORE INTO entities(id,kind,data) SELECT ?,'private_booking',? WHERE COALESCE((SELECT json_extract(value,'$.enabled') FROM settings WHERE key='privatePricing'),1)=1").bind(value.id,JSON.stringify(value)).run();if(!result.meta.changes){const concurrent=await db().prepare("SELECT data FROM entities WHERE id=? AND kind='private_booking'").bind(value.id).first<any>();if(concurrent){const v=JSON.parse(concurrent.data);if(v.mobile===p.mobile&&v.name===p.name)return publicView(v)}fail('TRIP_UNAVAILABLE',409)}return publicView(value)}
export async function lookupPrivate(body:any,req:Request){await rateLimit(req,'private-lookup',20);const code=key.parse(body.code).toUpperCase(),phone=mobile(key.parse(body.mobile));const r=await db().prepare("SELECT data FROM entities WHERE kind='private_booking' AND json_extract(data,'$.code')=? AND json_extract(data,'$.mobile')=?").bind(code,phone).first<any>();if(!r)fail('BOOKING_NOT_FOUND',404);return publicView(JSON.parse(r.data))}
export async function privateList(){const u=await requireStaff(['admin','driver']);const rows=(await db().prepare("SELECT data FROM entities WHERE kind='private_booking' "+(u.role==='driver'?"AND json_extract(data,'$.driver')=? AND json_extract(data,'$.status') IN ('confirmed','in_transit','completed') ":'')+"ORDER BY json_extract(data,'$.created') DESC LIMIT 300").bind(...(u.role==='driver'?[u.driverId]:[])).all<any>()).results.map(r=>JSON.parse(r.data));return{requests:rows,pricing:u.role==='admin'?await privateConfig():null}}
export async function updatePrivate(body:any){const u=await requireStaff(['admin','driver']);const b=z.object({id:key,version:z.number().int(),status:z.enum(['pending','confirmed','cancelled','in_transit','completed']),bus:z.string().max(180).optional(),driver:z.string().max(180).optional(),price:z.number().min(0).max(100000).optional(),endDate:date.optional(),endTime:time.optional(),paymentStatus:z.enum(['paid','unpaid']).optional(),paymentOnly:z.boolean().optional()}).parse(body);const row=await db().prepare("SELECT data FROM entities WHERE id=? AND kind='private_booking'").bind(b.id).first<any>();if(!row)fail('BOOKING_NOT_FOUND',404);const p=JSON.parse(row.data);if(p.version!==b.version)fail('CONFLICT',409);if(u.role!=='admin'&&(b.paymentStatus!==undefined||b.paymentOnly))fail('FORBIDDEN',403);
if(b.paymentOnly){if(!b.paymentStatus||b.status!==p.status||!['confirmed','in_transit','completed'].includes(p.status)||p.price===null)fail('INVALID_TRANSITION',409);const at=now(),previous=p.paymentStatus||'unpaid';const next={...p,paymentStatus:b.paymentStatus,updated:at,version:p.version+1,paymentEvents:[...(p.paymentEvents||[]),{from:previous,to:b.paymentStatus,amount:p.price,actor:u.email,at}]};const result=await db().prepare("UPDATE entities SET data=? WHERE id=? AND kind='private_booking' AND data=?").bind(JSON.stringify(next),p.id,row.data).run();if(!result.meta.changes)fail('CONFLICT',409);return{ok:true}}
if(b.paymentStatus!==undefined&&b.status!=='confirmed')fail('INVALID_TRANSITION',409);
if(u.role==='driver'&&(p.driver!==u.driverId||!((p.status==='confirmed'&&b.status==='in_transit')||(p.status==='in_transit'&&b.status==='completed'))))fail('FORBIDDEN',403);if(['cancelled','completed'].includes(p.status))fail('INVALID_TRANSITION',409);if(p.status==='in_transit'&&b.status!=='completed')fail('INVALID_TRANSITION',409);if(b.status==='completed'&&p.status!=='in_transit'||b.status==='in_transit'&&p.status!=='confirmed')fail('INVALID_TRANSITION',409);if(b.status==='in_transit'&&p.date!==today())fail('TRIP_NOT_TODAY');const next={...p,status:b.status,updated:now(),version:p.version+1};if(u.role==='admin'&&['pending','confirmed'].includes(p.status)&&['pending','confirmed'].includes(b.status)){next.bus=b.bus??p.bus;next.driver=b.driver??p.driver;next.price=b.price===undefined?p.price:Math.round(b.price*100);next.ends=b.endDate&&b.endTime?stamp(b.endDate,b.endTime):p.ends;if(next.ends<=next.starts||next.ends>next.starts+7*86400000||p.round&&next.ends<stamp(p.returnDate,p.returnTime))fail('INVALID_RETURN')}
if(next.status==='confirmed'||next.status==='in_transit'){const es=await entities();if(!es.some(e=>e.kind==='bus'&&e.id===next.bus&&(next.status==='in_transit'||e.active)&&e.seats===p.capacity)||!es.some(e=>e.kind==='driver'&&e.id===next.driver)||next.price===null)fail('PRIVATE_ASSIGNMENT_REQUIRED');if(next.status==='confirmed'&&next.starts<=now())fail('DATE_RANGE');for(let at=next.starts-86400000;at<next.ends+86400000;at+=86400000){const d=new Date(at+10800000).toISOString().slice(0,10);if(d>=today()&&Date.parse(d+'T00:00:00+03:00')<=now()+90*86400000)await materialize(d)}}
if(next.price!==p.price&&await db().prepare("SELECT id FROM entities WHERE id=? AND kind='invoice'").bind('invoice:'+p.code).first())fail('INVOICE_PRICE_LOCKED',409);
if((p.paymentStatus||'unpaid')==='paid'&&next.price!==p.price)fail('INVALID_TRANSITION',409);
next.paymentStatus=b.paymentStatus??p.paymentStatus??'unpaid';
if(next.paymentStatus!==(p.paymentStatus||'unpaid'))next.paymentEvents=[...(p.paymentEvents||[]),{from:p.paymentStatus||'unpaid',to:next.paymentStatus,amount:next.price,actor:u.email,at:next.updated}];
next.events=[...(p.events||[]),{status:next.status,paymentStatus:next.paymentStatus,at:next.updated,actor:u.email,price:next.price,bus:next.bus,driver:next.driver,ends:next.ends}];const assigned=['confirmed','in_transit'].includes(next.status);const result=await db().prepare((assigned?slotPrefix:'')+"UPDATE entities SET data=? WHERE id=? AND kind='private_booking' AND data=? AND (NOT EXISTS(SELECT 1 FROM entities inv WHERE inv.id='invoice:'||json_extract(entities.data,'$.code') AND inv.kind='invoice') OR json_extract(entities.data,'$.price')=?)"+(assigned?' AND '+resourceFree+" AND EXISTS(SELECT 1 FROM entities b WHERE b.kind='bus' AND b.id=json_extract(?,'$.bus') AND json_extract(b.data,'$.seats')=json_extract(?,'$.capacity') AND (json_extract(?,'$.status')='in_transit' OR COALESCE(json_extract(b.data,'$.active'),1)=1))":'' )).bind(...(assigned?[slotJSON(p.id,next.bus,next.driver,next.starts,next.ends)]:[]),JSON.stringify(next),p.id,row.data,next.price,...(assigned?[JSON.stringify(next),JSON.stringify(next),JSON.stringify(next)]:[])).run();if(!result.meta.changes)fail('ASSIGNMENT_CONFLICT',409);return{ok:true}}
