import {z} from 'zod';
import {db,entities,materialize,today,fail} from './arkan-server';
import {requireStaff,digest,randomToken} from './operations-auth';
const key=z.string().trim().min(1).max(180);
export async function issueBookingAccess(code:string){const token=randomToken();await db().batch([db().prepare('DELETE FROM booking_access WHERE expires<?').bind(Date.now()),db().prepare('INSERT INTO booking_access(token_hash,booking_code,expires) VALUES(?,?,?)').bind(await digest(token),code,Date.now()+24*60*60000)]);return token}
export async function bookingAccess(token:string){if(!/^[0-9a-f]{64}$/.test(token||''))fail('UNAUTHORIZED',401);const row=await db().prepare('SELECT booking_code FROM booking_access WHERE token_hash=? AND expires>?').bind(await digest(token),Date.now()).first<any>();if(!row)fail('TRACKING_EXPIRED',401);return row.booking_code as string}
export async function tracking(token:string){const code=await bookingAccess(token);const booking=await db().prepare('SELECT status FROM bookings WHERE code=?').bind(code).first<any>();const trips=(await db().prepare("SELECT DISTINCT t.id,t.date,t.time,t.from_station,t.to_station,t.bus,t.status,COALESCE(p.phase,'scheduled') phase,p.updated FROM tickets k JOIN trips t ON t.id=k.trip_id LEFT JOIN trip_progress p ON p.trip_id=t.id WHERE k.booking_code=? ORDER BY t.starts").bind(code).all<any>()).results;const events=booking.status==='cancelled'?[]:(await db().prepare('SELECT e.id,e.trip_id,e.phase,e.created FROM trip_events e WHERE EXISTS(SELECT 1 FROM tickets k WHERE k.trip_id=e.trip_id AND k.booking_code=?) ORDER BY e.created DESC').bind(code).all<any>()).results;return{code,status:booking.status,trips,events}}
export async function driverState(date:string){const user=await requireStaff(['driver']);await materialize(date);const trips=(await db().prepare("SELECT t.*,COALESCE(p.phase,'scheduled') phase,p.updated,p.actor FROM trips t LEFT JOIN trip_progress p ON p.trip_id=t.id WHERE t.driver=? AND (t.date=? OR (p.phase='in_transit' AND t.status='active')) ORDER BY t.starts").bind(user.driverId,date).all<any>()).results;const manifest=(await db().prepare("SELECT k.booking_code,k.trip_id,k.name,k.seat,k.boarded,b.mobile,COALESCE((SELECT json_extract(bm.data,'$.additionalMobile') FROM entities bm WHERE bm.id='booking:'||b.code AND bm.kind='booking_metadata'),'') additionalMobile,b.status FROM tickets k JOIN bookings b ON b.code=k.booking_code JOIN trips t ON t.id=k.trip_id LEFT JOIN trip_progress p ON p.trip_id=t.id WHERE t.driver=? AND (t.date=? OR (p.phase='in_transit' AND t.status='active')) AND b.status<>'cancelled' ORDER BY t.starts,k.seat").bind(user.driverId,date).all<any>()).results;return{user,trips,manifest,entities:(await entities()).filter(e=>e.kind==='station'||e.kind==='bus').map(e=>({...e}))}}
export async function transitionTrip(body:any){const u=await requireStaff(['driver','admin']);const b=z.object({trip:key,phase:z.enum(['boarding','in_transit','arrived'])}).parse(body);const tr=await db().prepare("SELECT t.*,COALESCE(p.phase,'scheduled') phase FROM trips t LEFT JOIN trip_progress p ON p.trip_id=t.id WHERE t.id=?").bind(b.trip).first<any>();if(!tr)fail('TRIP_NOT_FOUND',404);if(u.role==='driver'&&tr.driver!==u.driverId)fail('FORBIDDEN',403);if(tr.status!=='active')fail('TRIP_UNAVAILABLE',409);if(tr.phase===b.phase)return{ok:true,repeated:true};const prev={boarding:'scheduled',in_transit:'boarding',arrived:'in_transit'}[b.phase];if(tr.phase!==prev)fail('INVALID_TRANSITION',409);if(b.phase!=='arrived'&&tr.date!==today())fail('TRIP_NOT_TODAY',409);if(!tr.driver)fail('DRIVER_REQUIRED');const event=randomToken(),at=Date.now();const scope=u.role==='driver'?u.driverId:tr.driver;
const statements=[db().prepare("INSERT OR IGNORE INTO trip_events(id,trip_id,phase,created,actor) SELECT ?,id,?,?,? FROM trips t WHERE id=? AND status='active' AND driver=? AND COALESCE((SELECT phase FROM trip_progress WHERE trip_id=t.id),'scheduled')=?").bind(event,b.phase,at,u.email,b.trip,scope,prev),db().prepare('INSERT INTO trip_progress(trip_id,phase,updated,actor) SELECT trip_id,phase,created,actor FROM trip_events WHERE id=? ON CONFLICT(trip_id) DO UPDATE SET phase=excluded.phase,updated=excluded.updated,actor=excluded.actor').bind(event)];
const results=await db().batch(statements);if(!results[0].meta.changes){const current=await db().prepare('SELECT phase FROM trip_progress WHERE trip_id=?').bind(b.trip).first<any>();if(current?.phase===b.phase)return{ok:true,repeated:true};fail('INVALID_TRANSITION',409)}return{ok:true,event,phase:b.phase,at}}
export async function operationsFeed(date:string){await requireStaff(['admin','checkin']);const trips=(await db().prepare("SELECT t.id,t.driver,t.bus,t.date,t.time,t.from_station,t.to_station,t.status,COALESCE(p.phase,'scheduled') phase,p.updated,p.actor,(SELECT count(*) FROM tickets k JOIN bookings b ON b.code=k.booking_code WHERE k.trip_id=t.id AND b.status='paid') passengers,(SELECT count(*) FROM tickets k JOIN bookings b ON b.code=k.booking_code WHERE k.trip_id=t.id AND b.status='paid' AND k.boarded IS NOT NULL) boarded FROM trips t LEFT JOIN trip_progress p ON p.trip_id=t.id WHERE t.date=? OR (p.phase='in_transit' AND t.status='active') ORDER BY t.starts").bind(date).all<any>()).results;const events=(await db().prepare('SELECT e.* FROM trip_events e JOIN trips t ON t.id=e.trip_id WHERE t.date=? OR e.created>? ORDER BY e.created DESC LIMIT 100').bind(date,Date.now()-24*60*60000).all<any>()).results;return{trips,events,updated:Date.now()}}
