import {packageOffer} from '@/lib/package-reservations';
import {privateConfig,createPrivate,lookupPrivate,privateList,updatePrivate,savePrivatePricing} from '@/lib/private-booking';
import {paymentPolicy} from '@/lib/payment-policy';
import { z } from 'zod';
import {waitUntil} from 'cloudflare:workers';
import {driverState,transitionTrip,tracking,operationsFeed} from '@/lib/trip-operations';
import {pushConfig,subscribePush,queueEventPush,deliverPush,pushReport,retryPush} from '@/lib/trip-push';
import { seed,settings,publicPackages,entities,tripList,seats,makeHold,confirm,lookup,adminState,adminAction,adminSearch,adminBooking,today,fail,rateLimit } from '@/lib/arkan-server';
export const dynamic='force-dynamic';
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
async function handle(fn:()=>Promise<unknown>){try{await seed();return response(await fn())}catch(e:any){const validation=e instanceof z.ZodError||e instanceof SyntaxError;console.error('arkan',validation?'INVALID_INPUT':e.message);return response({error:validation?'INVALID_INPUT':e.status?e.message:'SERVICE_UNAVAILABLE'},validation?400:e.status||503)}}
export async function GET(req:Request){return handle(async()=>{const p=new URL(req.url).searchParams,op=p.get('op');if(op==='packageOffer'){const {raw,...offer}=await packageOffer(p.get('id')||'',p.get('departure')||'');return offer}if(op==='privateConfig')return privateConfig();if(op==='privateList')return privateList();if(op==='packages')return{packages:await publicPackages(),whatsapp:(await settings()).whatsapp||''};if(op==='config'){const cfg=await settings();return{settings:cfg,stations:await entities('station'),payments:paymentPolicy(cfg)}};if(op==='trips')return{trips:await tripList(p.get('date')||today(),p.get('from')||'',p.get('to')||'')};if(op==='seats')return{seats:await seats(p.get('trip')||'')};if(op==='pushConfig')return pushConfig();if(op==='driver'){const data=await driverState(p.get('date')||today());waitUntil(queueEventPush('').then(deliverPush).catch(()=>{}));return data}if(op==='operations'){const feed=await operationsFeed(p.get('date')||today());waitUntil(queueEventPush('').then(deliverPush).catch(()=>{}));return feed}if(op==='pushReport')return{rows:await pushReport()};if(op==='admin')return adminState(p.get('date')||today());if(op==='bookingDetail')return adminBooking(p.get('code')||'');if(op==='searchBookings')return{bookings:await adminSearch(p.get('q')||'',p.get('status')||'',p.get('date')||'')};fail('UNKNOWN_ACTION')})}
export async function POST(req:Request){return handle(async()=>{const origin=req.headers.get('origin');if(origin!==new URL(req.url).origin)fail('FORBIDDEN',403);if(!req.headers.get('content-type')?.includes('application/json'))fail('INVALID_INPUT');if(Number(req.headers.get('content-length')||0)>50000)fail('INVALID_INPUT');const text=await req.text();if(text.length>50000)fail('INVALID_INPUT');const b=JSON.parse(text);if(b.op==='tracking'){const data=await tracking(b.token);waitUntil(queueEventPush('').then(deliverPush).catch(()=>{}));return data}if(b.op==='subscribePush'){await rateLimit(req,'push-subscription',30);return subscribePush(b)}if(b.op==='retryPush'){const result=await retryPush();waitUntil(queueEventPush('').then(deliverPush).catch(()=>{}));return result}if(b.op==='tripPhase'){const result=await transitionTrip(b);await queueEventPush(result.event||'');waitUntil(deliverPush().catch(()=>{}));return result}if(b.op==='createPrivate')return createPrivate(b,req);if(b.op==='lookupPrivate')return lookupPrivate(b,req);if(b.op==='updatePrivate')return updatePrivate(b);if(b.op==='savePrivatePricing')return savePrivatePricing(b.data);if(b.op==='hold')return makeHold(b,req);if(b.op==='confirm')return confirm(b,req);if(b.op==='lookup'){if(String(b.code).toUpperCase().startsWith('PV-'))return{privateBooking:await lookupPrivate(b,req)};return lookup(b,req)};return adminAction(b)})}
