import { integer, text, sqliteTable, primaryKey, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const entities=sqliteTable('entities',{id:text('id').primaryKey(),kind:text('kind').notNull(),data:text('data').notNull()},t=>[index('entities_kind').on(t.kind)]);
export const trips=sqliteTable('trips',{id:text('id').primaryKey(),date:text('date').notNull(),time:text('time').notNull(),starts:integer('starts').notNull(),from:text('from_station').notNull(),to:text('to_station').notNull(),bus:text('bus').notNull(),driver:text('driver').notNull().default(''),status:text('status').notNull().default('active')},t=>[index('trips_route_date').on(t.from,t.to,t.date)]);
export const bookings=sqliteTable('bookings',{code:text('code').primaryKey(),holdToken:text('hold_token').notNull(),requestHash:text('request_hash').notNull(),mobile:text('mobile').notNull(),email:text('email').notNull(),amount:integer('amount').notNull(),status:text('status').notNull().default('demo'),created:integer('created').notNull(),refund:text('refund').notNull().default('none')},t=>[uniqueIndex('bookings_hold_token').on(t.holdToken),index('bookings_mobile').on(t.mobile),index('bookings_created').on(t.created)]);
export const holds=sqliteTable('holds',{trip:text('trip_id').notNull().references(()=>trips.id),seat:integer('seat').notNull(),token:text('token').notNull(),expires:integer('expires').notNull(),status:text('status').notNull().default('held')},t=>[primaryKey({columns:[t.trip,t.seat]}),index('holds_token').on(t.token)]);
export const tickets=sqliteTable('tickets',{id:text('id').primaryKey(),booking:text('booking_code').notNull().references(()=>bookings.code),trip:text('trip_id').notNull().references(()=>trips.id),seat:integer('seat').notNull(),name:text('name').notNull(),nationalId:text('national_id').notNull(),nationality:text('nationality').notNull(),boarded:integer('boarded'),staff:text('staff')},t=>[index('tickets_trip').on(t.trip),index('tickets_booking').on(t.booking),index('tickets_national_id').on(t.nationalId)]);
export const staff=sqliteTable('staff',{email:text('email').primaryKey(),role:text('role').notNull()});
export const limits=sqliteTable('limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});

export const holdGroups=sqliteTable('hold_groups',{token:text('token').primaryKey(),expires:integer('expires').notNull(),amount:integer('amount').notNull(),expected:integer('expected').notNull(),intent:text('intent').notNull()});

export const accounts=sqliteTable('accounts',{id:text('id').primaryKey(),email:text('email').notNull(),name:text('name').notNull(),role:text('role').notNull(),driverId:text('driver_id').notNull().default(''),passwordHash:text('password_hash').notNull(),mustChange:integer('must_change').notNull().default(0),active:integer('active').notNull().default(1),created:integer('created').notNull()},t=>[uniqueIndex('accounts_email').on(t.email)]);
export const sessions=sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),account:text('account_id').notNull().references(()=>accounts.id),expires:integer('expires').notNull()},t=>[index('sessions_account').on(t.account)]);
export const tripProgress=sqliteTable('trip_progress',{trip:text('trip_id').primaryKey().references(()=>trips.id),phase:text('phase').notNull(),updated:integer('updated').notNull(),actor:text('actor').notNull()});
export const tripEvents=sqliteTable('trip_events',{id:text('id').primaryKey(),trip:text('trip_id').notNull().references(()=>trips.id),phase:text('phase').notNull(),created:integer('created').notNull(),actor:text('actor').notNull()},t=>[uniqueIndex('trip_event_phase').on(t.trip,t.phase),index('trip_events_created').on(t.created)]);
export const bookingAccess=sqliteTable('booking_access',{tokenHash:text('token_hash').primaryKey(),booking:text('booking_code').notNull().references(()=>bookings.code),expires:integer('expires').notNull()},t=>[index('booking_access_booking').on(t.booking)]);
export const pushKeys=sqliteTable('push_keys',{id:text('id').primaryKey(),data:text('data').notNull()});
export const pushSubscriptions=sqliteTable('push_subscriptions',{id:text('id').primaryKey(),audience:text('audience').notNull(),subject:text('subject').notNull(),subscription:text('subscription').notNull(),locale:text('locale').notNull().default('ar'),created:integer('created').notNull()},t=>[index('push_subject').on(t.audience,t.subject)]);
export const pushOutbox=sqliteTable('push_outbox',{event:text('event_id').notNull().references(()=>tripEvents.id),subscription:text('subscription_id').notNull(),state:text('state').notNull().default('queued'),attempts:integer('attempts').notNull().default(0),updated:integer('updated').notNull(),error:text('error').notNull().default('')},t=>[primaryKey({columns:[t.event,t.subscription]})]);
